### ISSUE TITLE
Is anyone still here? The discord link has expired.

### ISSUE THREAD

**Issue by qianxliu** [Team-Donut/TeamDonut.tk#4]
I'm a common game developer enthusiast from China, and seek for a org just for interest

**Comment by khalby786** [comment]
Hey @Neteraxe,

Thanks for pointing this out!

While we will be updating our organization's description with a valid invite link, here's one for you to join now: https://discord.gg/8bnp2vK. Also, we are more active on Discord and we rarely update this GitHub organisation very less often. Consider this repo as kind of archived. 

Thanks again and have a great day! 😄

**Comment by qianxliu** [comment]
You're welcome
